DROP TABLE Person;
CREATE TABLE Person(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username varchar(100) NOT NULL,
    year_of_birth int NOT NULL,
    password varchar(100) NOT NULL
);

INSERT INTO Person(username, year_of_birth, password) VALUES('test_user1', 1980, 'test_password');

INSERT INTO Person(username, year_of_birth, password) VALUES('test_user2', 1980, 'test_password');

DELETE FROM Person;

SELECT * FROM Person;

TRUNCATE TABLE Person;

ALTER TABLE Person ADD COLUMN role varchar(100) NOT NULL;

INSERT INTO Person(username, year_of_birth, password, role) VALUES('test_user1', 1970, 'test_password', 'ROLE_USER');

UPDATE Person SET role='ROLE_ADMIN' WHERE username='admin';